### ISSUE TITLE
Proje geliştirmeleri

### ISSUE THREAD

**Issue by FlySquare** [herkobi/panel#4]
Merhaba, yapılacak görevleri tek tek issue olarak açacak mısınız? Belki üstlenebileceğim bir şeyler olabilir. yada readme de yapılacak maddelere başlandı mı acaba?  ayrıca dilerseniz kripto ödeme alt yapısı entegre edebilirim. https://coinpays.io [@CoinPays](https://github.com/coinpays-io)

**Comment by FlySquare** [comment]
@bulentsakarya @eyupinann @enesekinci

**Comment by bulentsakarya** [comment]
Merhaba. Şuan için dil dosyalarını tamamlama, paytr'yi tam entegre etme işlemleri var. Ayrıca ben bir tane sistem geliştiriyorum bu panel üzerinden, orada karşıma çıkan eksik / hata görürsem onu sisteme ekliyorum. Bu hafta sonu sanırım dil dosyalarını bitiririm ondan sonra ikinci betayı çıkaracağım. 

Sisteme yapı olarak yeni bir şey eklenmeyecek. Görülen eksik/hatalar düzenlenecek bu süreçte.
